server:
  port: 8100
  servlet:
    context-path: /api

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: true
            maxAge: 7200  # 2小时缓存
      routes:
        - id: system-service
          uri: http://localhost:8101
          predicates:
            - Path=/api/users/**

